//
//  File.swift
//  Proj
//
//  Created by Admin on 5/14/18.
//  Copyright © 2018 Admin. All rights reserved.
//

import Foundation

class dictLang {
    
    let dict = ["Azərbaycan":"az-AZ",
        "Shqiptar":"sq-AL",
        "አማርኛ":"am-ET",
        "English":"en-GB",
        
        "العربية":"ar-AE",
        
        "Հայերեն":"hy-AM",
        "Afrikaans":"af-ZA",
        "Euskal":"eu-ES",
        "Беларускі":"be-BY",
        "বাঙালি":"bn-IN",
        "Bermansky":"my-MY",
        "Български":"bg-BG",
        "Bosanski":"bs-BA",
        "Cymraeg":"cy-GB",
        "Magyar":"hu-HU",
        "Người việt nam":"vi-VN",
        "Hawaiian":"haw-US",
        "Galego":"gl-ES",
        "Ελληνικά":"el-GR",
        "ქართული":"ka-GE",
        "ગુજરાતી":"gu-IN",
        "Dansk":"da-DK",
        "Zulu":"zu-ZA",
        "עברית":"he-IL",
        "Igbo":"ig-NG",
        "ייִדיש":"yi-US",
        "Indonesian":"in-ID",
        "Gaeilge":"ga-IE",
        "Íslensku":"is-IS",
        "Español":"es-ES",
        "italiano":"it-IT",
        "Yorùbá":"yo-NG",
        "Қазақша":"kk-KZ",
        "ಕನ್ನಡ":"kn-IN",
        "Català":"ca-ES",
        "Кыргыз":"ky-KG",
        "中国":"zh-CN",
        "한국어":"ko-KR",
        "Kurmancî":"ku-TR",
        "ភាសាខ្មែរ":"km-KH",
        "ລາວ":"lo-LA",
        "Latviešu":"lv-LV",
        "Lietuviškai":"lt-LT",
        "Lëtzebuergesch":"lb-LU",
        "Македонски":"mk-MK",
        "Malagasy":"mg-MG",
        "Malayan":"ms-MY",
        "മലയാളം":"ml-IN",
        "Malti":"mt-MT",
        "Maori":"mi-NZ",
        "मराठी":"mr-IN",
        "Монгол хэл":"mn-MN",
        "Deutsch":"de-DE",
        "नेपाली":"ne-NP",
        "Nederland":"nl-NL",
        "Norsk":"no-NO",
        "ਪੰਜਾਬੀ":"pa-Arab",
        "فارسی":"fa-IR",
        "Polski":"pl-PL",
        "Português":"pt-PT",
        "پښتو":"ps-AF",
        "Românesc":"ro-RO",
        "Русский":"ru-RU",
        "Samoa":"sm-WS",
        "Српски":"sr-RS",
        "සිංහල":"si-LK",
        "سنڌي":"sd-IN",
        "Slovenský":"sk-SK",
        "Slovenščina":"sl-SI",
        "Somaliqui":"so-SO",
        "Kiswahili":"sw-KE",
        "Тоҷикӣ":"tg-TJ",
        "ไทย":"th-TH",
        "தமிழ்":"ta-IN",
        "తెలుగు":"te-IN",
        "Türk":"tr-TR",
        "O`zbek":"uz-UZ",
        "Український":"uk-UA",
        "اردو":"ur-PK",
        "Suomalainen":"fi-FI",
        "Français":"fr-FR",
        "Frysk":"fy-DE",
        "हिन्दी":"hi-IN",
        "Hrvatski":"hr-HR",
        "Česky":"cs-CZ",
        "Svenska":"sv-SE",
        "Alba":"gd-GB",
        "Esperanto":"eo",
        "Eesti":"et-EE",
        "日本語":"ja-JP"
    ]
    
    
}
